"""Add file indexes and unique constraint

Revision ID: 5ded862a5f02
Revises: 677b2479916f
Create Date: 2026-01-07 01:21:12.764348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ded862a5f02'
down_revision: Union[str, None] = '677b2479916f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_files_config_local_path', 'files', ['config_name', 'local_path'], unique=False)
    op.create_index('ix_files_config_page_unique', 'files', ['config_name', 'file_page'], unique=True)
    op.create_index('ix_files_config_size', 'files', ['config_name', 'file_size'], unique=False)
    op.create_index('ix_files_config_uploaded', 'files', ['config_name', 'uploaded'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_config_uploaded', table_name='files')
    op.drop_index('ix_files_config_size', table_name='files')
    op.drop_index('ix_files_config_page_unique', table_name='files')
    op.drop_index('ix_files_config_local_path', table_name='files')
    # ### end Alembic commands ###
