# --- Standart kategoriyalar (siz bergan) ---
STANDARD_CATEGORIES = {
    "movies": ["film", "kino", "фильм", "movies", "sinema", "кино", "movie", "cinema"],
    "series": ["serial", "сериал", "seriya", "seriallar", "tv series", "series"],
    "cartoons": ["multfilm", "multik", "мультфильм", "multfilmlar", "cartoon", "animated", "animation"],
    "anime": ["anime", "аниме", "yapon multfilmi", "japanese animation"],
    "documentary": ["dokumental", "documentary", "документальный", "hujjatli", "doc", "документалка"],
    "educational": ["ta'lim", "educational", "обучающий", "o'quv", "learn", "learning", "ta'limiy"],
    "entertainment": ["ko'ngilochar", "entertainment", "развлекательный", "show", "eglence"],
    "action": ["jangari", "boevik", "боевик", "экшн", "action", "harakat", "jang", "урушувчи"],
    "drama": ["drama", "драма", "dramatik", "dramatic", "hayotiy"],
    "comedy": ["komediya", "comedy", "комедия", "kulgili", "hazil", "funny", "комик"],
    "horror": ["qo'rqinchli", "ужасы", "horror", "daxshat", "qo'rquv", "scary", "страшный"],
    "sci-fi": ["fantastika", "sci-fi", "фантастика", "science fiction", "ilmiy fantastika", "sci fi"],
    "romance": ["romantika", "romance", "мелодрама", "sevgi", "muhabbat", "love", "romantic"],
    "fantasy": ["fentezi", "fantasy", "фэнтези", "sehrli", "magic", "magical", "сказочный"],
    "kids": ["bolalar", "детский", "kids", "children", "bola", "kichkintoylar", "family"],
    "music": ["musiqa", "music", "музыка", "qo'shiq", "song", "musical", "концерт", "клип"],
    "biography": ["biografiya", "биография", "biography", "hayot tarjimai holi", "life story"],
    "sport": ["sport", "спорт", "sports", "sportiv", "o'yin", "игра", "futbol", "basketball"],
    "history": ["tarix", "history", "исторический", "история", "historical", "tarixiy", "qadimiy"],
    "adventure": ["sarguzasht", "приключения", "adventure", "sayohat", "journey", "travel"],
    "thriller": ["triller", "thriller", "триллер", "hayajonli", "suspense", "qiziqarli"],
    "crime": ["kriminal", "crime", "криминал", "jinoyat", "criminal", "detective", "детективный"],
    "mystery": ["sirli", "mystery", "мистика", "sir", "mystical", "supernatural", "загадочный"],
    "tv_shows": ["tv", "шоу", "телепередача", "show", "tv show", "teledastur", "program"],
    "concerts": ["konsert", "concert", "концерт", "jonli ijro", "live", "performance"],
    "stories": ["hikoya", "story", "рассказ", "ertaklar", "tale", "qissa", "skazka"],
    "adult_movies": ["18+", "kattalar", "эротика", "adult", "erotica", "mature", "взрослый"],
    "comedy_club": ["comedy club", "qvz", "stand up", "komedi klub", "hazil", "юмор"],
    "romantic_comedy": ["romantic comedy", "romantik komediya", "rom com", "sevgi komediyasi"],
    "space_adventure": ["kosmik", "space", "космос", "space adventure", "astronaut", "kosmonavt"],
    "true_crime": ["haqiqiy jinoyat", "true crime", "реальные преступления", "criminal case"],
    "war_history": ["urush", "war", "война", "urush tarixi", "military", "harbiy", "battle"],
    "anime_action": ["anime action", "аниме боевик", "yapon jangari", "anime fight"],
    "kids_songs": ["bolalar qo'shiqlari", "kids songs", "детские песни", "bola qo'shiqlari"],
    "rock_concerts": ["rock concert", "рок концерт", "rock music", "rok musiqa", "heavy metal"],
    "fantasy_series": ["fantasy series", "фэнтези сериал", "sehrli serial", "magical series"],
    "sports_documentary": ["sports doc", "спорт документальный", "sport haqida", "sportiv hujjatli"],
    "tv_game_shows": ["teleo'yin", "game show", "игровое шоу", "o'yin dasturi", "викторина"],

    # --- Yangi kategoriyalar ---
    "western": ["western", "вестерн", "g'arbiy", "kovboy", "cowboy", "дикий запад"],
    "psychological": ["psixologik", "psychological", "психологический", "ruhiy", "mental"],
    "disaster": ["ofat", "disaster", "катастрофа", "tabiat ofati", "natural disaster"],
    "superhero": ["superqahramon", "superhero", "супергерой", "qahramon", "marvel", "dc"],
    "spy": ["ayg'oqchi", "spy", "шпион", "razvedka", "agent", "secret agent"],
    "musical": ["mjuzikl", "musical", "мюзикл", "qo'shiqli", "singing", "opera"],
    "family": ["oilaviy", "family", "семейный", "oila", "family friendly", "all ages"],
    "cooking": ["oshpazlik", "cooking", "кулинария", "taom", "food", "chef", "recipe"],
    "travel": ["sayohat", "travel", "путешествие", "turizm", "tourism", "exploration"],
    "nature": ["tabiat", "nature", "природа", "wildlife", "yovvoyi tabiat", "animals"],
    "technology": ["texnologiya", "technology", "технология", "tech", "innovation", "IT"],
    "medical": ["tibbiyot", "medical", "медицинский", "doctor", "hospital", "medicine"],
    "legal": ["huquqiy", "legal", "юридический", "court", "judge", "law", "lawyer"],
    "fashion": ["moda", "fashion", "мода", "style", "beauty", "go'zallik", "design"],
    "business": ["biznes", "business", "бизнес", "entrepreneur", "tadbirkor", "company"],
    "politics": ["siyosat", "politics", "политика", "government", "hukumat", "election"],
    "religion": ["din", "religion", "религия", "spiritual", "ruhiy", "faith"],
    "paranormal": ["g'ayritabiiy", "paranormal", "паранормальный", "ghost", "arvoh", "supernatural"],
    "zombie": ["zombi", "zombie", "зомби", "undead", "o'lik", "apocalypse"],
    "vampire": ["vampir", "vampire", "вампир", "bloodsucker", "qon so'ruvchi"],
    "martial_arts": ["jang san'ati", "martial arts", "боевые искусства", "kung fu", "karate"],
    "survival": ["omon qolish", "survival", "выживание", "wilderness", "desert island"],
    "heist": ["o'g'irlik", "heist", "ограбление", "robbery", "bank robbery", "theft"],
    "prison": ["qamoqxona", "prison", "тюрьма", "jail", "inmates", "mahkum"],
    "apocalypse": ["apokalipsis", "apocalypse", "апокалипсис", "end times", "oxirat"],
    "time_travel": ["vaqt sayohati", "time travel", "путешествие во времени", "time machine"],
    "alien": ["begona", "alien", "инопланетянин", "extraterrestrial", "UFO"],
    "pirates": ["qaroqchilar", "pirates", "пираты", "corsair", "buccaneer", "sea"],
    "medieval": ["o'rta asr", "medieval", "средневековый", "knight", "castle", "qal'a"],
    "post_apocalyptic": ["apokalipsisdan keyin", "post apocalyptic", "постапокалипсис"],
    "cyberpunk": ["kiberpank", "cyberpunk", "киберпанк", "futuristic", "cyber"],
    "steampunk": ["stimpank", "steampunk", "стимпанк", "victorian", "steam engine"],
    "noir": ["noir", "нуар", "qora", "dark", "detective noir", "crime noir"],
    "mockumentary": ["soxta hujjatli", "mockumentary", "псевдодокументальный", "fake documentary"],
    "found_footage": ["topilgan tasvirlar", "found footage", "найденные кадры"],
    "anthology": ["antologiya", "anthology", "антология", "collection", "to'plam"],
    "reality_tv": ["realiti shou", "reality tv", "реалити шоу", "reality show"],
    "talk_show": ["tok shou", "talk show", "ток шоу", "interview", "suhbat"],
    "game_show": ["o'yin shou", "game show", "игровое шоу", "quiz", "viktorina"],
    "news": ["yangiliklar", "news", "новости", "journalism", "jurnalistika"],
    "podcast": ["podkast", "podcast", "подкаст", "audio show", "radio"],
    "standup_comedy": ["stand up", "standup comedy", "стендап", "solo comedy"],
    "sketch_comedy": ["sketch", "sketch comedy", "скетч", "comedy sketch"],
    "improv": ["improvizatsiya", "improv", "импровизация", "improvisational"],
    "magic": ["sehr", "magic", "магия", "sehrbozlik", "magic show", "illusion"],
    "circus": ["sirk", "circus", "цирк", "carnival", "karnaval", "acrobat"],
    "dance": ["raqs", "dance", "танец", "ballet", "balet", "choreography"],
    "fitness": ["fitnes", "fitness", "фитнес", "workout", "exercise", "jismoniy"],
    "yoga": ["yoga", "йога", "meditation", "meditatsiya", "spiritual practice"],
    "extreme_sports": ["ekstremal sport", "extreme sports", "экстремальный спорт"],
    "racing": ["poyga", "racing", "гонки", "formula", "car racing", "moto"],
    "wrestling": ["kurash", "wrestling", "борьба", "WWE", "professional wrestling"],
    "boxing": ["boks", "boxing", "бокс", "fight", "jang", "MMA"],
    "football": ["futbol", "football", "футбол", "soccer", "FIFA", "world cup"],
    "basketball": ["basketbol", "basketball", "баскетбол", "NBA", "dunking"],
    "tennis": ["tennis", "теннис", "wimbledon", "racket", "court"],
    "golf": ["golf", "гольф", "putting", "golf course", "tournament"],
    "swimming": ["suzish", "swimming", "плавание", "pool", "olympics", "diving"],
}


CATEGORY_MAP = {
    1: "other",
    2: "general",
    3: "entertainment", 
    4: "educational",
    5: "thriller",
    6: "comedy",
    7: "drama",
    8: "action",
    9: "romance",
    10: "horror",
    11: "sci_fi",
    12: "fantasy",
    13: "documentary",
    14: "music",
    15: "kids",
    16: "family",
    17: "sport",
    18: "history",
    19: "biography",
    20: "crime",
    21: "mystery",
    22: "adventure",
    23: "western",
    24: "war",
    25: "anime",
    26: "cartoons",
    27: "series",
    28: "movies",
    29: "series",
    30: "cartoons",
    31: "anime",
    32: "documentary",
    33: "educational",
    34: "entertainment",
    35: "action",
    36: "drama",
    37: "comedy",
    38: "horror",
    39: "sci-fi",
    40: "romance",
    41: "fantasy",
    42: "kids",
    43: "music",
    44: "biography",
    45: "sport",
    46: "history",
    47: "adventure",
    48: "thriller",
    49: "crime",
    50: "mystery",
    51: "tv_shows",
    52: "concerts",
    53: "stories",
    54: "adult_movies",
    55: "comedy_club",
    56: "romantic_comedy",
    57: "space_adventure",
    58: "true_crime",
    59: "war_history",
    60: "anime_action",
    61: "kids_songs",
    62: "rock_concerts",
    63: "fantasy_series",
    64: "sports_documentary",
    65: "tv_game_shows",

    # --- Yangi kategoriyalar ID lari ---
    66: "western",
    67: "psychological", 
    68: "disaster",
    69: "superhero",
    70: "spy",
    71: "musical",
    72: "family",
    73: "cooking",
    74: "travel",
    75: "nature",
    76: "technology",
    77: "medical",
    78: "legal",
    79: "fashion",
    80: "business",
    81: "politics",
    82: "religion",
    83: "paranormal",
    84: "zombie",
    85: "vampire",
    86: "martial_arts",
    87: "survival",
    88: "heist",
    89: "prison",
    90: "apocalypse",
    91: "time_travel",
    92: "alien",
    93: "pirates",
    94: "medieval",
    95: "post_apocalyptic",
    96: "cyberpunk",
    97: "steampunk",
    98: "noir",
    99: "mockumentary",
    100: "found_footage",
    101: "anthology",
    102: "reality_tv",
    103: "talk_show",
    104: "game_show",
    105: "news",
    106: "podcast",
    107: "standup_comedy",
    108: "sketch_comedy",
    109: "improv",
    110: "magic",
    111: "circus",
    112: "dance",
    113: "fitness",
    114: "yoga",
    115: "extreme_sports",
    116: "racing",
    117: "wrestling",
    118: "boxing",
    119: "football",
    120: "basketball",
    121: "tennis",
    122: "golf",
    123: "swimming",
}


# Reverse mapping (nom → id)
CATEGORY_NAME_TO_ID = {v: k for k, v in CATEGORY_MAP.items()}
